travis:
  secure:
    BINSTAR_TOKEN: M+865jj/l9g+V5g066qvy07VyppzbQYHRVB1LqvoWUFloqMxpq2yxBcjkqLZJzVSIq7LQsVny6hsks8pNkJa2ljOjx4EfDKXMLT+MYCYt2r9sGltvZRoySGcwf73hMzJ8+gOJp6LGbzHTB3nnyt11oKba7XzOOX07tXU6NM946il3MD3a0y7vxUVv11Ip+q1ebEvzVhEg3kXRT/zrB7yzM9G67DNBds4xKGplkCXhhl4OdIshnKJDROBHrABRTyvyIY19tvt5FGcGGkluP6nBntK4nJM5jBCxQxfdfOVKEZDfWB/G3Bjx9tkjBpklHkXKD3gJg1HMROQe4GU/CS8QQizgWTpHG/QUx+KSs0Hn9cfBu86bJFD5wymyTZUSfBpSmb8S87+oUv1HLE+T5TFshb4zCpqMLgP6tyJiuscNRjx/4UpChKZXXPOabugnT8OyVzLRn6SQ0b4TFtL6Ojg3H0WjgX8r+xzznmrZPR8AjAHVsPO97nFP8Fhbi8Pa1DxFCEqAeX9uYYLJov3zccl629OFx7ZUkVTk2TO28mblZJWXnLtgNfnK0T3c9ODRaEad9cTfV2i/aYLcMqmzDeJea17RRaCGk9OjutkMgqKjfLiS+gK46W93XsOvWVS0+AB6BWol2D0ilxK1nKhHvMrnTdjC8nXn6YNg9hqzYh/1As=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
